site_title = "MyArxiv"
limit_days = 7
cache_url = "https://zoeabcd.github.io/MyArxiv/cache.json"

[[sources]]
limit = 150
category = "cs.CC"
title = "Computational Complexity"

[[sources]]
limit = 150
category = "cs.CR"
title = "Cryptography and Security"

[[sources]]
limit = 150
category = "cs.DM"
title = "Discrete Mathematics"

[[sources]]
limit = 150
category = "cs.CC"
title = "Computational Complexity"

# [[sources]]
# limit = 150
# category = "cs.MM"
# title = "Multimedia"

[scripts]
highlight_title = "scripts/highlight_title.rhai"
highlight_author = "scripts/highlight_author.rhai"
highlight_conference = "scripts/highlight_conference.rhai"
